### ISSUE TITLE
Need ability to generate json for preview/draft items

### ISSUE THREAD

**Issue by niedfelj** [contentful/contentful-bootstrap.rb#62]
Would be great to have this feature

**Comment by dlitvakb** [comment]
Hey @niedfelj,

This sounds like an interesting feature to have, and easy enough to add.

That said, the way the gem currently works. It will publish all content once it's used to create/update the space.

So also something like a `--no-publish` option should be added alongside this feature.

How does that sound?

Cheers

**Comment by niedfelj** [comment]
I started working on it, this isn't complete obviously

https://github.com/contentful/contentful-bootstrap.rb/pull/63/files

I was running out of memory (we have 1500 draft items!), and we would need pagination for the API.

Is there not the ability to store whether content is published or not and then put them back in the same state?

**Comment by dlitvakb** [comment]
Currently there is no way of doing that.

What we can probably do, is add an optional array to the base object just like there is for `entries`, `assets` and `content_types`, called something like `avoid_publish`. But this introduces the new complexity of having a "negative status", which is definitely far from ideal.

Another option is to add to the `sys` object of each object a `"publish": false` key, though sadly there is no way of actually differentiating draft content from published content on the Preview API, so there's no actual way of doing this without some kind of manual work.

So, once again, I think that having the `--no-publish` option is something that definitely has to go along-side this feature, as it's something that you do on all content, or you don't, unless very explicitly said otherwise. But there is no way to know what content is published and what content is not just by retrieving content from the Preview API.

What I suggest doing, when this `preview` feature is available, is the following:
* Generate 2 templates, one with the content on the Delivery API, and another one with the content on the Preview API.
* Create/Update a space with the template from the Delivery API.
* Update said space with the template from the Preview API using the `--no-publish` flag.

That way you can keep the content in sync.

Does this make sense?

Cheers

**Comment by niedfelj** [comment]
That makes sense. Thanks!

**Comment by niedfelj** [comment]
The output from this seems perfect, maybe we should attempt to make it the same for parity?

https://github.com/contentful/contentful-export

contentful-export --space-id <SPACE ID> --management-token <MANAGEMENT TOKEN> --include-drafts

**Comment by dlitvakb** [comment]
Hey @niedfelj,

There have been talks on making the output of both tools match, but we haven't found yet the time to do it, as it would require quite a sizeable change on any of the tools that is the one changing.

But we do feel that it would be a good thing to do in the future, as both tools do have really good use cases, and having interchangeable templates would be something really good.

Cheers
